### ISSUE TITLE
Diesel CLI not detecting dotenv file

### ISSUE THREAD

**Issue by Arthurdw** [diesel-rs/diesel#2681]
## Setup

Create a dotenv file and place your config in it, then run any of the diesel commands that require a DB conn.

### Versions

- **Rustup:** `1.23.1`
- **Rustc:** `1.50.0`
- **Cargo:** `1.50.0`
- **Diesel:** `1.4.1`
- **Database:** `PostgreSQL 13.2-1 (Debian)`
- **Operating System**:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

## Problem Description

![CLI](https://the-earth.is-inside.me/IQmedfPp.png)
 
 As seen in the screenshot, the diesel cli does not detect my dotenv file in my project.
 
 **NOTE: The credentials that are shown are from a localhost test docker database**

### What are you trying to accomplish?

Run any diesel cli command that interacts with the database.

### What is the expected output?

That it runs the command and interacts with the database.

### What is the actual output?

`The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.`

### Are you seeing any additional errors?

No

### Steps to reproduce

Create a dotenv file with the following configuration, and then run any diesel command that should interact with the database.

```env
DATABASE_TYPE = postgres
DATABASE_USERNAME = postgres
DATABASE_PASSWORD = admin
DATABASE_HOST = localhost
DATABASE_DATABASE = accounts

DATABASE_URL = "${DATABASE_TYPE}://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_DATABASE}"
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by Mingun** [comment]
You mispelled some variables: `DATBASE_USERNAME`, `DATBASE_PASSWORD` (missing "A" in datAbase)

**Comment by Arthurdw** [comment]
> You mispelled some variables: `DATBASE_USERNAME`, `DATBASE_PASSWORD` (missing "A" in datAbase)

Oops, this doesn't cause the issue tho. (I checked, still returns the `The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.`)

**Comment by Arthurdw** [comment]
I just did a little test, it does not even relate to my dotenv config. It just does not detect the dotenv file in general. I cleared my dotenv file and placed the following content in it and it resulted in the same problem.
```
DATABASE_URL=postgres://postgres:admin@localhost/accounts
```

**Comment by Arthurdw** [comment]
I'm using [Set-PsEnv](https://github.com/rajivharris/Set-PsEnv) to load my env file now, and this seems to fix the problem.

**Comment by henryboisdequin** [comment]
I'm not having this issue and as this is resolved on your end, maybe this issue can be closed

cc @diesel-rs/reviewers

**Comment by henryboisdequin** [comment]
@Arthurdw are you still experiencing this issue?

**Comment by Arthurdw** [comment]
No, the issue has been resolved.

**Comment by erayerdin** [comment]
I am having the issue with Bash on Ubuntu 21.04. `diesel migration run` complains with the same message. Tried restarting the terminal and the system, but the problem persists. I use it with Rocket.

**Comment by sudhirdhumal289** [comment]
Facing same issue...
using:
rust 1.57.0
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.15.0"

cross verified .env file multiple times no luck
using workspace but dependencies, files generated are at module level

**Comment by weiznich** [comment]
@sudhirdhumal289 Our issue tracker is no support forum, so please don't comment on old issues without adding new information. Use the discussion part of the repo to ask questions. Also it might be useful to include the relevant parts of your code as otherwise its not possible to help you.
